### ISSUE TITLE
SSH private key invalid format

### ISSUE THREAD

**Issue by elkan1788** [tzzs/server-shell#3]
Thanks for your share this action script.

```yaml
uses: tzzs/server-shell@v3
    with:
      IP: ${{ secrets.TC_HOST }}
      USERNAME: ${{ secrets.TC_USER }}
      PRIVATE_KEY: ${{ secrets.TC_PRIVATE_KEY }}
      SHELL: |
        "sh /home/lighthouse/myblog-deploy.sh"
```

At first time used your script all things were well, but recently that found ssh script execute failed, then output the error message as below:

```shell
/usr/bin/ssh server sh /home/***/myblog-deploy.sh
Warning: Permanently added '***' (ECDSA) to the list of known hosts.
Load key "/home/runner/.ssh/deploy.key": invalid format
Permission denied, please try again.
Permission denied, please try again.
***@***: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Error: Error: The process '/usr/bin/ssh' failed with exit code 255
```

At this time I don't change my sercets variables , I don't know what's happend, and need your help, Thanks.

**Comment by tzzs** [comment]
1. May you could check whether the black line in the private_key
2. If not working, please try to use `ssh-keygen` to generate a new key and replace it.

**Comment by elkan1788** [comment]
Ok, that found it was my misstake,  after I check the private key content found that is use OPEN SSL  type which build under Windows OS not the RSA type. Seems the github action had changed some rules when run script in recently.  And the generate the ssh-key use RSA type , all things running well. 

So there suggest write the  ssh-key type in document will help people who want use this action script.

Thanks.
